In [2]:
from scipy.io import loadmat
import numpy as np

In [188]:
def getDAtrend(DAtrend, t1, t2, data_type='smoothed'):
    """
    Python version of MATLAB getDAtrend.
    
    Parameters:
        DAtrend: loaded MATLAB struct (as a list or array of objects)
        t1, t2: trial window indices (integers)
        dataType: 'raw' or 'smooth' (default: 'raw')
    Returns:
        stats: double array of size (numAnimals, 1)
    """

    # Determine dataType field
    if 'smooth' in data_type:
        key = 'slopeMap_smoothed'
    else:
        key = 'slopeMap_raw'

    stats = np.full(len(DAtrend), np.nan)

    for a in range(len(DAtrend)):
        try:
            field_data = DAtrend[a][key]
            if t1 <= 0: t1_final = field_data.shape[0] + t1
            else: t1_final = t1
            if t2 <= 0: t2_final = field_data.shape[1] + t2
            else: t2_final = t2

            if (t1_final > field_data.shape[0] or t2_final > field_data.shape[1]
                or t1_final <= 0 or t2_final <= 0 or t1 > t2_final):
                stats[a] = np.nan
            else:
                stats[a] = field_data[t1_final-1, t2_final-1]  # MATLAB is 1-based, Python is 0-based
        except Exception as e:
            print(f"Error accessing data for animal {a},: {e}")
            stats[a] = np.nan

    return stats


def getDAvsEImap(DAvsEImap, key='smoothed', direction='reverse', nTrials=50):
    """ 
    Parameters:
        DAvsEImap: loaded MATLAB struct (as a list or array of objects)
        key: 'smoothed' or 'raw' (default: 'smoothed')
    Returns:
        stats: double array of size (numAnimals, 1)
    """

    map_data = DAvsEImap[key][0]
    nTrials = map_data.shape[0] // 2

    if direction == 'reverse':
        late_ticks = -np.flip(np.arange(1, nTrials + 1))  # flip(1:nTrials)
        late_idx = map_data.shape[0] + late_ticks

    sub_map = map_data[np.ix_(late_idx, late_idx)]
    rotated_map = np.rot90(sub_map, k=-1)

In [100]:
DAtrend = loadmat('/Users/shunli/Desktop/manim_projects/DAtrend_manim.mat')
DAtrend = DAtrend['DAtrend_manim'].flatten()

In [191]:
i, j = 10, 20

stats = getDAtrend(DAtrend, t1=i-50, t2=j-50, data_type='smooth')
stats

array([        nan, -0.03716697,  0.23243363, -0.15672018, -0.17411836,
       -0.04764319, -0.1335437 , -0.20848667,  0.08482569, -0.06749392,
        0.01627971,  0.0905859 , -0.19026525,  0.00990848,  0.07180059,
       -0.06522659, -0.01709673, -0.01495578,  0.12400629,  0.13673453,
        0.11997311,  0.26527528,  0.13452264, -0.01911747, -0.34563817,
        0.05340152, -0.25898138,         nan,         nan,         nan])

In [134]:
DAvsEImap = loadmat('/Users/shunli/Desktop/manim_projects/DAvsEImap_manim.mat')
DAvsEImap = DAvsEImap['DAvsEImap_manim'].flatten()
DAvsEImap['smoothed'][0].shape

(140, 140)

In [161]:
map_data = DAvsEImap['smoothed'][0]

nTrials = 50
late_ticks = -np.flip(np.arange(1, nTrials + 1))  # flip(1:nTrials)
late_idx = map_data.shape[0] + late_ticks     # mimic MATLAB indexing
late_idx

array([ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
       103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
       116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
       129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139])

In [162]:
sub_map = map_data[np.ix_(late_idx, late_idx)]
sub_map

array([[        nan,         nan, -0.37217849, ...,  3.73084528,
         4.07629224,  4.51779021],
       [        nan,         nan,         nan, ...,  4.37050231,
         4.74634133,  5.17044959],
       [        nan,         nan,         nan, ...,  3.73877433,
         4.00600115,  4.33945838],
       ...,
       [        nan,         nan,         nan, ...,         nan,
                nan,  0.18853457],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan]], shape=(50, 50))

In [182]:
animalEI_mat = loadmat('/Users/shunli/Desktop/manim_projects/animalEIpeaks.mat')
animalEI = animalEI_mat['animalEIindex_peaks']

In [183]:
animalEI

array([[ 0.09239674],
       [ 0.03965995],
       [-0.42226602],
       [-0.08940776],
       [-0.18445254],
       [ 0.25400178],
       [-0.22965684],
       [-0.56444827],
       [ 0.78973906],
       [-0.00993123],
       [-0.27625927],
       [-0.74943796],
       [-0.72454838],
       [-0.20890144],
       [-0.12799995],
       [-0.0646866 ],
       [-0.2379009 ],
       [-0.37428537],
       [-0.01373143],
       [ 0.05648903],
       [ 0.46759495],
       [ 0.16417774],
       [ 0.03385522],
       [ 0.25977921],
       [ 0.33743203],
       [ 0.45291995],
       [-0.02182647],
       [ 0.31510599],
       [ 0.18485642],
       [ 0.17420487]])